name: "Release a new version"

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select release type"
        type: choice
        options:
          - patch
          - minor
          - major
        required: true

jobs:
  release:
    name: "Execute release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.GH_DEPLOY_KEY_PRIVATE }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm ci

      # Docs https://github.com/release-it/release-it/blob/main/docs/github-releases.md#automated
      # https://github.com/settings/tokens to generate token with repo access
      - run: npm run release ${{ github.event.inputs.release_type }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
