name: Build and deploy Storefront

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    name: Build Storefront
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Initialize git config & install dependencies
        run: |
          git config --global user.name "$(git log HEAD --pretty='%aN')"
          git config --global user.email "$(git log HEAD --pretty='%aE')"
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            sfra-webpack-builder/package-lock.json
            storefront-reference-architecture/package-lock.json
      - run: |
          npm ci
          npm run sfra:install

      - name: Compile static files
        run: |
          npm run dev

      - name: Cache sfcc-ci
        id: cache-sfcc-ci
        uses: actions/cache@v4
        with:
          path: /usr/local/bin
          key: sfcc-ci

      - name: Download and install sfcc-ci binary
        if: steps.cache-sfcc-ci.outputs.cache-hit != 'true'
        run: |
          sudo curl -sL https://github.com/SalesforceCommerceCloud/sfcc-ci/releases/download/v2.11.0/sfcc-ci-linux -o /usr/local/bin/sfcc-ci
          sudo chmod +x /usr/local/bin/sfcc-ci

      - name: Deploy to Development
        env:
          SFCC_OAUTH_CLIENT_ID: ${{ secrets.SFCC_OAUTH_CLIENT_ID }}
          SFCC_OAUTH_CLIENT_SECRET: ${{ secrets.SFCC_OAUTH_CLIENT_SECRET }}
          HOST: ${{ secrets.DEV_HOST }}
        run: |
          SHA=${{ github.sha }}
          SHORT_SHA=$(echo $SHA | cut -c 1-8)
          BUILD_NAME=development-${SHORT_SHA}-build-${{ github.run_number }}
          npm run code:zip -- -r ${BUILD_NAME}
          sfcc-ci client:auth
          sfcc-ci code:deploy dist/${BUILD_NAME}.zip -i ${HOST} --activate

  test:
    needs: build
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          git config --global user.name "$(git log HEAD --pretty='%aN')"
          git config --global user.email "$(git log HEAD --pretty='%aE')"
      - uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
          cache: 'npm'
          cache-dependency-path: |
            test/package-lock.json
      - run: |
          cd test
          npm ci
          npx playwright install

      - name: Run Unit Tests
        run: |
          cd test
          npm run test:unit

      - name: Run UI Tests
        env:
          BASE_URL: ${{ secrets.DEV_STOREFRONT_URL }}
        run: |
          cd test
          npm run test:sfra:e2e
